[project]
name = "yt-dlp-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=11.3.0",
    "pyinstaller>=6.16.0",
    "yt-dlp>=2026.1.29",
    "yt-dlp-ejs>=0.4.0",
]
